# -*- coding: utf-8 -*-
{'name': 'Salesforce Connector',
 'version': '8.0.1.0.0',
 'author': 'Camptocamp,Odoo Community Association (OCA)',
 'category': 'Connector',
 'depends': ['connector', 'sale', 'product'],
 'summary': """Provides core synchronization interfaces with Salesforce.""",
 'data': [
     'salesforce_backend/view/backend_model_view.xml',
     'salesforce_account/view/backend_view.xml',
     'salesforce_contact/view/backend_view.xml',
     'salesforce_contact/view/res_partner_view.xml',
     'salesforce_product/view/backend_view.xml',
     'salesforce_price_book_entry/view/backend_view.xml',
     'salesforce_opportunity/view/backend_view.xml',
     'security/ir.model.access.csv',
     'data/cron.xml',
 ],
 'external_dependencies': {'python': ['simple_salesforce', 'requests']},
 'installable': True,
 'auto_install': False,
 'license': 'AGPL-3',
 'application': False,
 }
